# Generated by Django 4.2.2 on 2023-07-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroFracturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('cdcomprador', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('contratista', models.CharField(max_length=50)),
                ('codigopr', models.CharField(max_length=6)),
                ('producto', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('precio', models.PositiveIntegerField()),
                ('precioTotal', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
    ]
