# Generated by Django 4.2.2 on 2023-07-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroFracturacion', '0003_alter_ventas_apellido_alter_ventas_cdcomprador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='dicodig',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cdcomprador',
            field=models.CharField(max_length=12),
        ),
    ]
