# Generated by Django 4.2.2 on 2023-07-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroFracturacion', '0005_rename_dicodig_ventas_di'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='di',
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cdcomprador',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
