# Generated by Django 4.2.2 on 2023-07-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroFracturacion', '0006_remove_ventas_di_alter_ventas_cdcomprador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='di',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cdcomprador',
            field=models.CharField(max_length=12),
        ),
    ]
