# Generated by Django 4.2.2 on 2023-08-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroFracturacion', '0009_recibo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
