# Generated by Django 4.2.2 on 2023-08-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroFracturacion', '0013_ventas_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
