# Generated by Django 4.2.2 on 2023-08-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroFracturacion', '0015_factura_pago_facturatemp_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='pago',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='facturatemp',
            name='pago',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='pago',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='pago',
            field=models.BooleanField(),
        ),
    ]
