# Generated by Django 4.2.2 on 2024-02-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroFracturacion', '0017_contratista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratista',
            name='id',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
